version: '2'

services:

  redis:
    image: redis
    restart: always

  web:
    build:
      context: ./web/
    restart: always
    volumes:
      - ./web/app:/app

    ports:
      - "8000:8000"
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web
